# Installations, imports, utils

In [1]:
!pip install transformers==4.33.0 accelerate==0.22.0 einops==0.6.1 langchain==0.0.300 xformers==0.0.21 \
bitsandbytes==0.41.1 sentence_transformers==2.2.2 chromadb==0.4.12 --quiet

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-pubsublite 1.8.2 requires overrides<7.0.0,>=6.0.1, but you have overrides 7.7.0 which is incompatible.
jupyterlab-lsp 4.2.0 requires jupyter-lsp>=2.0.0, but you have jupyter-lsp 1.5.1 which is incompatible.
torchdata 0.6.0 requires torch==2.0.0, but you have torch 2.0.1 which is incompatible.

In [2]:
!pip install rouge-score==0.0.4 nltk==3.8.1 bert-score==0.3.11 --quiet

import numpy as np
import torch
from sklearn.metrics import precision_score, recall_score
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer
from bert_score import score as bert_score
from transformers import GPT2LMHeadModel, GPT2Tokenizer

import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.translate.meteor_score import meteor_score

from transformers import GPT2LMHeadModel, GPT2Tokenizer

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
preprocessing 0.1.13 requires nltk==3.2.4, but you have nltk 3.8.1 which is incompatible.

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...

In [3]:
from torch import cuda, bfloat16
import torch
import transformers
from transformers import AutoTokenizer
from time import time

from langchain.llms import HuggingFacePipeline
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.chains import RetrievalQA
from langchain.vectorstores import Chroma

# Initialize model, tokenizer, query pipeline

Define the model, the device, and the `bitsandbytes` configuration.

In [4]:
model_id = '/kaggle/input/llama-2/pytorch/7b-chat-hf/1'

device = f'cuda:{cuda.current_device()}' if cuda.is_available() else 'cpu'

# this requires the `bitsandbytes` library
bnb_config = transformers.BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=bfloat16
)

Prepare the model and the tokenizer.

In [5]:
time_1 = time()
model_config = transformers.AutoConfig.from_pretrained(
    model_id,
)
model = transformers.AutoModelForCausalLM.from_pretrained(
    model_id,
    trust_remote_code=True,
    config=model_config,
    quantization_config=bnb_config,
    device_map='auto',
)
tokenizer = AutoTokenizer.from_pretrained(model_id)
time_2 = time()
print(f"Prepare model, tokenizer: {round(time_2-time_1, 3)} sec.")

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Prepare model, tokenizer: 185.604 sec.

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(

Define the query pipeline.

In [6]:
time_1 = time()
query_pipeline = transformers.pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        torch_dtype=torch.float16,
        device_map="auto",)
time_2 = time()
print(f"Prepare pipeline: {round(time_2-time_1, 3)} sec.")

Prepare pipeline: 1.484 sec.

We define a function for testing the pipeline.

In [7]:
def test_model(tokenizer, pipeline, prompt_to_test):
    """
    Perform a query
    print the result
    Args:
        tokenizer: the tokenizer
        pipeline: the pipeline
        prompt_to_test: the prompt
    Returns
        None
    """
    # adapted from https://huggingface.co/blog/llama2#using-transformers
    time_1 = time()
    sequences = pipeline(
        prompt_to_test,
        do_sample=True,
        top_k=10,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        max_length=2048,)
    time_2 = time()
    print(f"Test inference: {round(time_2-time_1, 3)} sec.")
    for seq in sequences:
        print(f"Result: {seq['generated_text']}")

## Test the query pipeline

We test the pipeline with a query about the meaning of State of the Union (SOTU).

In [8]:
test_model(tokenizer,
           query_pipeline,
           "Please explain what is the State of the Union address. Give just a definition. Keep it in 100 words.")

/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py:1417: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(

Test inference: 8.166 sec.
Result: Please explain what is the State of the Union address. Give just a definition. Keep it in 100 words.
The State of the Union address is an annual speech delivered by the President of the United States to Congress, in which they report on the current state of the nation, highlight their accomplishments, and propose new policies and initiatives. The address has been a tradition since 1790 and is seen as an important moment for the President to set the legislative agenda and rally the country around a common vision.

In [137]:
import pandas as pd

data = pd.read_csv('/kaggle/input/glassdoor-company-insightsscraped-data-collection/glassdoor_comany.csv', encoding='latin1')
data

,Company Name,Company rating,Company reviews,Company salaries,Company Jobs,Location,Number of Employees,Industry Type,Company Description
0,Amazon,3.8,168.8K,201.7K,201.7K,25 office locations in United States,10000+ Employees,Internet & Web Services,"All Amazon teams and businesses, from Prime de..."
1,Deloitte,4.1,97.2K,167.4K,167.4K,23 office locations in United States,10000+ Employees,Accounting & Tax,Think a professional services career is nothin...
2,Target,3.6,75K,116.1K,116.1K,4 office locations in United States,10000+ Employees,General Merchandise & Superstores,Target is one of the worlds most recognized b...
3,McDonald's,3.5,117K,71.7K,71.7K,110 N Carpenter Street,10000+ Employees,Restaurants & Cafes,McDonalds is proud to be one of the most reco...
4,Accenture,4.0,145.1K,53.6K,53.6K,United States,10000+ Employees,Business Consulting,Accenture is a global professional services co...
...,...,...,...,...,...,...,...,...,...
9935,Furman University,4.0,169,229,229,United States,501 to 1000 Employees,Colleges & Universities,"This school's slogan could be, ""Go Further tha..."
9936,Kilwin's Chocolates,3.8,186,192,192,United States,51 to 200 Employees,Food & Beverage Manufacturing,TOA Global is the market leader in dedicated o...
9937,TOA Global,4.3,618,21,21,United States,1001 to 5000 Employees,HR Consulting,Insurance broking and risk management solution...
9938,JLT Group,3.7,543,51,51,United States,5001 to 10000 Employees,Insurance Agencies & Brokerages,A steakhouse experience should be unforgettabl...
9939,Sullivan's Steakhouse,3.5,181,176,176,13 office locations in United States,1001 to 5000 Employees,Restaurants & Cafes,NaN

In [138]:
data= data[:200]
data

,Company Name,Company rating,Company reviews,Company salaries,Company Jobs,Location,Number of Employees,Industry Type,Company Description
0,Amazon,3.8,168.8K,201.7K,201.7K,25 office locations in United States,10000+ Employees,Internet & Web Services,"All Amazon teams and businesses, from Prime de..."
1,Deloitte,4.1,97.2K,167.4K,167.4K,23 office locations in United States,10000+ Employees,Accounting & Tax,Think a professional services career is nothin...
2,Target,3.6,75K,116.1K,116.1K,4 office locations in United States,10000+ Employees,General Merchandise & Superstores,Target is one of the worlds most recognized b...
3,McDonald's,3.5,117K,71.7K,71.7K,110 N Carpenter Street,10000+ Employees,Restaurants & Cafes,McDonalds is proud to be one of the most reco...
4,Accenture,4.0,145.1K,53.6K,53.6K,United States,10000+ Employees,Business Consulting,Accenture is a global professional services co...
...,...,...,...,...,...,...,...,...,...
195,Randstad US,3.7,5.1K,11.1K,11.1K,25 office locations in United States,5001 to 10000 Employees,HR Consulting,Randstad is the global leader in the HR servic...
196,Adecco,3.7,8.7K,5K,5K,"10151 Deerwood Park Blvd, Bldg 400",201 to 500 Employees,Staffing & Subcontracting,"eBay is where the world goes to shop, sell, an..."
197,eBay,4.1,5.4K,9.4K,9.4K,15 office locations in United States,10000+ Employees,Internet & Web Services,UST is a global digital transformations soluti...
198,UST,3.9,7.2K,9.6K,9.6K,8 office locations in United States,10000+ Employees,Information Technology Support Services,Genpact (NYSE: G) is a global professional ser...
199,Genpact,4.0,19.7K,3.8K,3.8K,17 office locations in United States,10000+ Employees,Information Technology Support Services,NaN

In [140]:
data.drop(['Company reviews', 'Company salaries', 'Company Jobs', 'Number of Employees'], axis=1, inplace=True)
data

/tmp/ipykernel_32/154685627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(['Company reviews', 'Company salaries', 'Company Jobs', 'Number of Employees'], axis=1, inplace=True)

,Company Name,Company rating,Location,Industry Type,Company Description
0,Amazon,3.8,25 office locations in United States,Internet & Web Services,"All Amazon teams and businesses, from Prime de..."
1,Deloitte,4.1,23 office locations in United States,Accounting & Tax,Think a professional services career is nothin...
2,Target,3.6,4 office locations in United States,General Merchandise & Superstores,Target is one of the worlds most recognized b...
3,McDonald's,3.5,110 N Carpenter Street,Restaurants & Cafes,McDonalds is proud to be one of the most reco...
4,Accenture,4.0,United States,Business Consulting,Accenture is a global professional services co...
...,...,...,...,...,...
195,Randstad US,3.7,25 office locations in United States,HR Consulting,Randstad is the global leader in the HR servic...
196,Adecco,3.7,"10151 Deerwood Park Blvd, Bldg 400",Staffing & Subcontracting,"eBay is where the world goes to shop, sell, an..."
197,eBay,4.1,15 office locations in United States,Internet & Web Services,UST is a global digital transformations soluti...
198,UST,3.9,8 office locations in United States,Information Technology Support Services,Genpact (NYSE: G) is a global professional ser...
199,Genpact,4.0,17 office locations in United States,Information Technology Support Services,NaN

In [141]:
import pandas as pd

# Define bins and labels
bins = [0, 2.5, 4, 5]
labels = [1, 2, 3]

# Add the Security column
data['Security'] = pd.cut(data['Company rating'], bins=bins, labels=labels, include_lowest=True)
data

/tmp/ipykernel_32/3763719133.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Security'] = pd.cut(data['Company rating'], bins=bins, labels=labels, include_lowest=True)

,Company Name,Company rating,Location,Industry Type,Company Description,Security
0,Amazon,3.8,25 office locations in United States,Internet & Web Services,"All Amazon teams and businesses, from Prime de...",2
1,Deloitte,4.1,23 office locations in United States,Accounting & Tax,Think a professional services career is nothin...,3
2,Target,3.6,4 office locations in United States,General Merchandise & Superstores,Target is one of the worlds most recognized b...,2
3,McDonald's,3.5,110 N Carpenter Street,Restaurants & Cafes,McDonalds is proud to be one of the most reco...,2
4,Accenture,4.0,United States,Business Consulting,Accenture is a global professional services co...,2
...,...,...,...,...,...,...
195,Randstad US,3.7,25 office locations in United States,HR Consulting,Randstad is the global leader in the HR servic...,2
196,Adecco,3.7,"10151 Deerwood Park Blvd, Bldg 400",Staffing & Subcontracting,"eBay is where the world goes to shop, sell, an...",2
197,eBay,4.1,15 office locations in United States,Internet & Web Services,UST is a global digital transformations soluti...,3
198,UST,3.9,8 office locations in United States,Information Technology Support Services,Genpact (NYSE: G) is a global professional ser...,2
199,Genpact,4.0,17 office locations in United States,Information Technology Support Services,NaN,2

In [142]:
df=data
df.columns = ['Company Name', 'Company Rating', 'Location', 'Industry Type', 'Company Description', 'Security']
df

,Company Name,Company Rating,Location,Industry Type,Company Description,Security
0,Amazon,3.8,25 office locations in United States,Internet & Web Services,"All Amazon teams and businesses, from Prime de...",2
1,Deloitte,4.1,23 office locations in United States,Accounting & Tax,Think a professional services career is nothin...,3
2,Target,3.6,4 office locations in United States,General Merchandise & Superstores,Target is one of the worlds most recognized b...,2
3,McDonald's,3.5,110 N Carpenter Street,Restaurants & Cafes,McDonalds is proud to be one of the most reco...,2
4,Accenture,4.0,United States,Business Consulting,Accenture is a global professional services co...,2
...,...,...,...,...,...,...
195,Randstad US,3.7,25 office locations in United States,HR Consulting,Randstad is the global leader in the HR servic...,2
196,Adecco,3.7,"10151 Deerwood Park Blvd, Bldg 400",Staffing & Subcontracting,"eBay is where the world goes to shop, sell, an...",2
197,eBay,4.1,15 office locations in United States,Internet & Web Services,UST is a global digital transformations soluti...,3
198,UST,3.9,8 office locations in United States,Information Technology Support Services,Genpact (NYSE: G) is a global professional ser...,2
199,Genpact,4.0,17 office locations in United States,Information Technology Support Services,NaN,2

In [143]:
from langchain.schema import Document

docs = []
for _, row in df.iterrows():
    content = f"""
Company: {row['Company Name']}
Rating: {row['Company Rating']}
Location: {row['Location']}
Industry: {row['Industry Type']}
Description: {row['Company Description']}
"""
    docs.append(
        Document(page_content=content.strip(), metadata={"security_level": int(row['Security'])})
    )

In [144]:
docs

[Document(page_content='Company: Amazon\nRating: 3.8\nLocation: 25 office locations in United States\nIndustry: Internet & Web Services\nDescription: All Amazon teams and businesses, from Prime delivery to AWS, are guided by four key tenets: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking. We are driven by the excitement of building technologies, inventing products, and providing services that transform the way our customers live their lives and run their businesses.', metadata={'security_level': 2}),
 Document(page_content='Company: Deloitte\nRating: 4.1\nLocation: 23 office locations in United States\nIndustry: Accounting & Tax\nDescription: Think a professional services career is nothing but spreadsheets, gray suits, and corporate profits? Think again. From professional growth to pursuing your passions, careers at Deloitte come with plenty of opportunities. Our range of services and depth of resources create the potential to make an impact through most any career. Right now, our professionals are working closely with organizations that seek to enable social change, spark disruptive technologies, fund cures for diseases, implement sustainability solutions, prevent identity theft, foster inclusive cultures, enhance trust in the capital markets, and a lot more.', metadata={'security_level': 3}),
 Document(page_content='Company: Target\nRating: 3.6\nLocation: 4 office locations in United States\nIndustry: General Merchandise & Superstores\nDescription: Target is one of the world\x92s most recognized brands and one of America\x92s leading retailers. Serving guests at over 1,800 stores nationwide and on Target.com, we make Target our guests\x92 preferred shopping destination by offering outstanding value, inspiration, innovation and an exceptional guest experience that no other retailer can deliver. Target is committed to responsible corporate citizenship, ethical business practices, environmental stewardship and generous community support. Since 1946, we have given 5 percent of our profits back to our communities. Our goal is to work as one team to fulfill our unique brand promise to our guests, wherever and whenever they choose to shop.', metadata={'security_level': 2}),
 Document(page_content="Company: McDonald's\nRating: 3.5\nLocation: 110 N Carpenter Street\nIndustry: Restaurants & Cafes\nDescription: McDonald\x92s is proud to be one of the most recognized brands in the world, with restaurants in over 100 countries and billions of customers served each year. As the global leader in the food service industry, we have a legacy of innovation and hard work that continues to drive us. Today, we are growing with velocity and are focused on modernizing our experiences, not to make a different McDonald\x92s but to build a better McDonald\x92s. About 80% of the restaurants are run by franchisees or affiliates.", metadata={'security_level': 2}),
 Document(page_content='Company: Accenture\nRating: 4.0\nLocation: United States\nIndustry: Business Consulting\nDescription: Accenture is a global professional services company with leading capabilities in digital, cloud and security. Combining unmatched experience and specialized skills across more than 40 industries, we offer Strategy and Consulting, Interactive, Technology and Operations services \x97 all powered by the world\x92s largest network of Advanced Technology and Intelligent Operations centers. Our 624,000 people deliver on the promise of technology and human ingenuity every day, serving clients in more than 120 countries. We embrace the power of change to create value and shared success for our clients, people, shareholders, partners and communities. Visit us at www.accenture.com.', metadata={'security_level': 2}),
 Document(page_content='Company: IBM\nRating: 4.0\nLocation: 2 office locations in United States\nIndustry: Information Technology Support Services\nDescription: IBM works to design, advance, and scale the technologies that define each era. Restlessly reinventing since 1911, we are one of the largest technology, consulting and research companies in the world. IBMers are agents of change \x96 in this team, you\x92ll become a part of a historic, prestigious, and global community in which you\x92ll be respected, and your talents will have a real impact. Join our team of experts and thrive in a collaborative and friendly environment where you can bring your whole self at work. Use your skills to empower clients and partners to create something that is bigger than what any one of us could produce alone. Come and let\x92s create together!', metadata={'security_level': 2}),
 Document(page_content="Company: Microsoft\nRating: 4.4\nLocation: 34 office locations in United States\nIndustry: Computer Hardware Development\nDescription: Tata Consultancy Services is an IT services, consulting and business solutions organization that has been partnering with many of the world\x92s largest businesses in their transformation journeys for over 50 years. TCS offers a consulting-led, cognitive powered, integrated portfolio of business, technology and engineering services and solutions. This is delivered through its unique Location Independent Agile\x99 delivery model, recognized as a benchmark of excellence in software development. A part of the Tata group, India's largest multinational business group, TCS has over 528,000 of the world\x92s best-trained consultants in 46 countries. The company generated consolidated revenues of US $22.2 billion in the fiscal year ended March 31, 2021 and is listed on the BSE (formerly Bombay Stock Exchange) and the NSE (National Stock Exchange) in India. TCS' proactive stance on climate change and award-winning work with communities across the world have earned it a place in leading sustainability indices such as the MSCI Global Sustainability Index and the FTSE4Good Emerging Index. For more information, visit www.tcs.com", metadata={'security_level': 3}),
 Document(page_content="Company: Tata Consultancy Services\nRating: 3.9\nLocation: 38 office locations in United States\nIndustry: Software Development\nDescription: Cognizant (NASDAQ-100: CTSH) is one of the world's leading professional services companies, transforming clients' business, operating and technology models for the digital era. Our unique industry-based, consultative approach helps clients envision, build and run more innovative and efficient businesses. Headquartered in the U.S., Cognizant is ranked 230 on the Fortune 500 and is consistently listed among the most admired companies in the world. Learn how Cognizant helps clients lead with digital at www.cognizant.com. To apply for open positions, visit https://careers.cognizant.com", metadata={'security_level': 2}),
 Document(page_content='Company: Cognizant Technology Solutions\nRating: 3.8\nLocation: 25 office locations in United States\nIndustry: Information Technology Support Services\nDescription: By bringing people together over coffee, Starbucks has become one of the world\x92s best-known and best-loved companies. We purchase, roast and serve award-winning coffee. We also offer Italian-style espresso beverages, cold blended beverages, delicious food, premium teas and selected compact discs through our retail stores. Working at Starbucks is a lot like working with your friends. When you work here, you\x92re not an \x93employee\x94 \x96 we call ourselves \x93partners\x94 because we believe in shared common goals and mutual success. We\x92re dedicated to serving ethically sourced coffee, caring for the environment and giving back to the communities where we do business.', metadata={'security_level': 2}),
 Document(page_content='Company: Starbucks\nRating: 3.7\nLocation: 7 office locations in United States\nIndustry: Restaurants & Cafes\nDescription: nan', metadata={'security_level': 2}),
 Document(page_content='Company: Google\nRating: 4.4\nLocation: United States\nIndustry: Internet & Web Services\nDescription: Since our founding in 1998, Google has grown by leaps and bounds. Starting from two computer science students in a university dorm room, we now have over a hundred thousand employees and over one hundred offices around the world. These Googlers build products that help create opportunities for everyone, whether down the street or across the globe. So whether you want to be a part of developing innovative technology, campaigns, products or partnerships, your work here is a chance to accomplish things that matter. To learn more about our job opportunities, teams, offices, benefits and workplace culture, visit careers.google.com.', metadata={'security_level': 3}),
 Document(page_content='Company: The Home Depot\nRating: 3.8\nLocation: 2455 Paces Ferry Rd. SE, Atlanta, GA, 30339\nIndustry: Home Furniture & Housewares Stores\nDescription: You may\x92ve seen our stores in your neighborhood because if you\x92re like 90% of the U.S. population, you live within 10 miles of one of our stores. Our 2,200 retail stores are an important part of our company and it takes a big behind-the-scenes team too. Let\x92s look at some of the reasons why more than 400,000 people choose to work with us: \x95 We are the world\x92s largest home improvement retailer. Our scale and resources let us have a huge impact on the world of retail and in local communities. \x95 In addition to our stores, we have distribution centers across the country and corporate offices in several major cities. There\x92s a good chance your next opportunity could be right in your backyard. \x95 We take care of our people. Competitive pay, consistent schedules, great benefits, and even pet insurance are just a few of the highlights. \x95 Over 35,000 veterans are continuing their careers with us. We value their unique skills, and we also help military spouses maintain and grow their careers when they move. \x95 We have an inclusive, diverse culture, and we believe in giving back. Here, you can be yourself and be part of something much bigger. We\x92re proud to be recognized for being a great place to work by the following groups: \x95 Forbes Best Employers for Diversity 2020 \x95 Comparably: Happiest Employees \x96 Large Company Category and Best Companies for Work-Life Balance \x95 Mogul Top 100 Workplaces with the Greatest D&amp;I Initiatives \x95 Military Friendly Employer \x96 since 2001 \x95 Forbes Best Employers for New Grads', metadata={'security_level': 2}),
 Document(page_content='Company: EY\nRating: 3.9\nLocation: United States\nIndustry: Accounting & Tax\nDescription: At EY, you will work with entrepreneurs, the biggest companies and entire countries to solve their most pressing challenges. We promise you an exceptional experience that is yours to build \x97 using our opportunities, scale, technology, learning, and diverse and inclusive culture. And what you do here matters, guided by our purpose of building a better working world \x97 for our people, for our clients and for our communities. We help digital pioneers fight data piracy, guide governments through cash flow crises, unlock new medical treatments with data analytics, and pursue high-quality audits to build trust in financial markets and business. With over 365,000 people in more than 150 countries, we\x92re one of the world\x92s leading professional services organizations, with four integrated service lines: Assurance, Consulting, Strategy and Transactions, and Tax. Our global reach, skills and ability to learn from different perspectives help us create positive change on a massive scale.', metadata={'security_level': 2}),
 Document(page_content='Company: Apple\nRating: 4.2\nLocation: 20 office locations in United States\nIndustry: Computer Hardware Development\nDescription: We\x92re a diverse collective of thinkers and doers, continually reimagining what\x92s possible to help us all do what we love in new ways. And the same innovation that goes into our products also applies to our practices \x97 strengthening our commitment to leave the world better than we found it. This is where your work can make a difference in people\x92s lives. Including your own. Apple is an equal opportunity employer that is committed to inclusion and diversity. Visit apple.com/careers to learn more.', metadata={'security_level': 3}),
 Document(page_content='Company: PwC\nRating: 3.9\nLocation: 32 office locations in United States\nIndustry: Accounting & Tax\nDescription: Our people are powered by technology to turn today\x92s ideas into tomorrow\x92s solutions. Learn more about how you can help organizations meet the challenges and opportunities of the US marketplace in the areas of audit, tax, consulting and products and technology. We connect people with diverse backgrounds and skillsets to solve important problems together\x97for our clients, our communities and for the world at large.', metadata={'security_level': 2}),
 Document(page_content='Company: US Army\nRating: 3.8\nLocation: 42 office locations in United States\nIndustry: National Agencies\nDescription: The US Department of the Army has its marching orders. One of the three military departments (along with the Air Force and Navy) of the US Department of Defense, the Army provides ground-based military forces to deter and fight wars and protect the security of the US. The army has more than 675,000 soldiers, including active duty soldiers (nearly 75%) and reservists (Army National Guard and Army Reserves). Army personnel are deployed in about 80 countries. The Army operates about 40 forts throughout the US and has bases in Africa, Europe, Japan, the Middle East, and South Korea.', metadata={'security_level': 2}),
 Document(page_content='Company: Wells Fargo\nRating: 3.7\nLocation: 25 office locations in United States\nIndustry: Banking & Lending\nDescription: Wells Fargo & Company (NYSE: WFC) is a leading financial services company that has approximately $1.9 trillion in assets, proudly serves one in three U.S. households and more than 10% of small businesses in the U.S. Wells Fargo is No. 41 on Fortune\x92s 2022 rankings of America\x92s largest corporations. In the communities we serve, the company focuses its social impact on building a sustainable, inclusive future for all by supporting housing affordability, small business growth, financial health, and a low-carbon economy. We ranked #3 on the 2022 LinkedIn Top Companies list \x96 and #1 among financial services companies \x96 as the best workplace \x93to grow your career\x94 in the U.S. For more information, visit wellsfargo.com | Twitter: @wellsfargo', metadata={'security_level': 2}),
 Document(page_content='Company: Oracle\nRating: 3.9\nLocation: 30 office locations in United States\nIndustry: Enterprise Software & Network Solutions\nDescription: Oracle is the world\x92s leading provider of business software. But you probably already knew that. With a presence in over 175 countries, we are one of the biggest technology companies on the planet. What you might not know is that we are leading a cloud revolution. We\x92re using emerging technologies like AI, machine learning, and blockchain to solve critical real-world problems. From advancing energy efficiency to reimagining online commerce, the work we do is not only transforming the world of business\x97it\x92s helping governments, powering nonprofits, and giving billions of people the tools they need to outpace change and make a difference.', metadata={'security_level': 2}),
 Document(page_content="Company: Bank of America\nRating: 4.0\nLocation: 25 office locations in United States\nIndustry: Banking & Lending\nDescription: Bank of America is one of the world's largest financial institutions, serving individuals, small- and middle-market businesses and large corporations with a full range of banking, investing, asset management and other financial and risk management products and services. The company serves approximately 56 million U.S. consumer and small business relationships. It is among the world's leading wealth management companies and is a global leader in corporate and investment banking and trading.", metadata={'security_level': 2}),
 Document(page_content='Company: AT&T\nRating: 3.7\nLocation: 25 office locations in United States\nIndustry: Telecommunications Services\nDescription: Looking for a new way to connect? You\x92re in the right place. We are in the business of connection \x96 to our customers, our communities, and each other. We are invested in building strong networks, future facing technology solutions, and career opportunities that have a global impact. We want to give you 4 reasons why you should join #LifeAtATT. 1. Whether you\x92re pursuing a career in sales, technology, or something else entirely, you\x92re ready to connect to something bigger. 2. We\x92ve got opportunities all over the globe to do what you love. 3. Living our values \x96 standing for equality, pursuing excellence, and thinking big \x96 is right in your wheelhouse. 4. You like great benefits. Ready? It\x92s all waiting for you at att.jobs, and while you\x92re at it check out #LifeAtATT to get the latest on how we\x92re living, working, and playing. We hope to connect with you soon!', metadata={'security_level': 2}),
 Document(page_content="Company: Lowe's Home Improvement\nRating: 3.5\nLocation: 1000 Lowe's Blvd. Mooresville, NC 28117\nIndustry: Home Furniture & Housewares Stores\nDescription: Lowe\x92s Companies, Inc. (NYSE: LOW) is a FORTUNE® 35 home improvement company serving approximately 19 million customers a week in the United States. With the fiscal year 2022 sales of nearly $97 billion, Lowe\x92s and its related businesses operate or service more than 1,700 home improvement and hardware stores and employ over 300,000 associates. Based in Mooresville, N.C., Lowe\x92s supports the communities it serves through programs focused on creating safe, affordable housing and helping to develop the next generation of skilled trade experts. For more information, visit Lowes.com.", metadata={'security_level': 2}),
 Document(page_content="Company: UPS\nRating: 3.5\nLocation: 25 office locations in United States\nIndustry: Taxi & Car Services\nDescription: Every day at UPS, our people are responsible for the movement of goods, funds and information in more than 200 countries and territories. As UPS has evolved from a Seattle-based bike messenger company into a multi-billion-dollar global corporation, our team has held a singular focus\x97empowering commerce around the world. Today, UPS is the world's largest package delivery company and a leading global provider of specialized transportation and logistics services. Whether we\x92re connecting with global giants or local mom and pop businesses, our people are at work improving distribution networks and managing supply chains\x97helping our customers to do what they do best. UPS makes the world work better.", metadata={'security_level': 2}),
 Document(page_content='Company: Qualcomm\nRating: 4.1\nLocation: 16 office locations in United States\nIndustry: Computer Hardware Development\nDescription: Qualcomm is a company of inventors designing the cutting-edge wireless technologies the world runs on.', metadata={'security_level': 3}),

In [145]:
from langchain.text_splitter import CharacterTextSplitter

text_splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=50)
split_docs = text_splitter.split_documents(docs)

In [146]:
model_name = "sentence-transformers/all-mpnet-base-v2"
model_kwargs = {"device": "cuda"}

embedding_model = HuggingFaceEmbeddings(model_name=model_name, model_kwargs=model_kwargs)

In [147]:
from langchain.vectorstores import Chroma

vectordb = Chroma.from_documents(
    documents=split_docs,
    embedding=embedding_model,
    persist_directory="chroma_db"  # can be saved for later use
)
vectordb.persist()

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

In [148]:
def secure_retrieve(query, agent_level, top_k=2):
    retriever = vectordb.as_retriever(search_kwargs={"k": top_k})
    results = retriever.get_relevant_documents(query)
    
    filtered = [
        doc for doc in results if doc.metadata.get("security_level", 0) <= agent_level
    ]
    
    if not filtered:
        return "Access Denied — Clearance Insufficient." if results else "Oops!! No matching data found."

    return "\n\n".join([doc.page_content for doc in filtered])

In [89]:
pip install langchain --upgrade

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Requirement already satisfied: langchain in /opt/conda/lib/python3.10/site-packages (0.0.300)
Collecting langchain
  Downloading langchain-0.3.23-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 33.0 MB/s eta 0:00:00
Collecting langchain-core<1.0.0,>=0.3.51 (from langchain)
  Downloading langchain_core-0.3.51-py3-none-any.whl (423 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.3/423.3 kB 39.0 MB/s eta 0:00:00
Collecting langchain-text-splitters<1.0.0,>=0.3.8 (from langchain)
  Downloading langchain_text_splitters-0.3.8-py3-none-any.whl (32 kB)
Collecting langsmith<0.4,>=0.1.17 (from langchain)
  Downloading langsmith-0.3.30-py3-none-any.whl (358 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.2/358.2 kB 37.1 MB/s eta 0:00:00
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Downloading pydantic-2.11.3-py3-none-any.whl (443 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.6/443.6 kB 41.0 MB/s eta 0:00:00
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /opt/conda/lib/python3.10/site-packages (from langchain) (2.0.17)
Requirement already satisfied: requests<3,>=2 in /opt/conda/lib/python3.10/site-packages (from langchain) (2.31.0)
Requirement already satisfied: PyYAML>=5.3 in /opt/conda/lib/python3.10/site-packages (from langchain) (6.0)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /opt/conda/lib/python3.10/site-packages (from langchain) (4.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/conda/lib/python3.10/site-packages (from langchain-core<1.0.0,>=0.3.51->langchain) (8.2.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /opt/conda/lib/python3.10/site-packages (from langchain-core<1.0.0,>=0.3.51->langchain) (1.33)
Collecting packaging<25,>=23.2 (from langchain-core<1.0.0,>=0.3.51->langchain)
  Downloading packaging-24.2-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 8.2 MB/s eta 0:00:00
Collecting typing-extensions>=4.7 (from langchain-core<1.0.0,>=0.3.51->langchain)
  Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 6.7 MB/s eta 0:00:00
Collecting httpx<1,>=0.23.0 (from langsmith<0.4,>=0.1.17->langchain)
  Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 9.8 MB/s eta 0:00:00
Collecting orjson<4.0.0,>=3.9.14 (from langsmith<0.4,>=0.1.17->langchain)
  Downloading orjson-3.10.16-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.8/132.8 kB 15.5 MB/s eta 0:00:00
Collecting requests-toolbelt<2.0.0,>=1.0.0 (from langsmith<0.4,>=0.1.17->langchain)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 6.2 MB/s eta 0:00:00
Collecting zstandard<0.24.0,>=0.23.0 (from langsmith<0.4,>=0.1.17->langchain)
  Downloading zstandard-0.23.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 20.2 MB/s eta 0:00:0000:01:00:01
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting pydantic-core==2.33.1 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading pydantic_core-2.33.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 84.6 MB/s eta 0:00:00
Collecting typing-inspection>=0.4.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading typing_inspection-0.4.0-py3-none-any.whl (14 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2->langchain) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2->langchain) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2->langchain) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2->langchain) (2023.7.22)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.10/site-packages (from SQLAlchemy<3,>=1.4->langchain) (2.0.2)
Requirement already satisfied: anyio in /opt/conda/lib/python3.10/site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (3.7.0)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain)
  Downloading httpcore-1.0.8-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 9.1 MB/s eta 0:00:00
Requirement already satisfied: h11<0.15,>=0.13 in /opt/conda/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/conda/lib/python3.10/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.51->langchain) (2.0)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.10/site-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (1.3.0)
Requirement already satisfied: exceptiongroup in /opt/conda/lib/python3.10/site-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (1.1.1)
Installing collected packages: zstandard, typing-extensions, packaging, orjson, httpcore, annotated-types, typing-inspection, requests-toolbelt, pydantic-core, httpx, pydantic, langsmith, langchain-core, langchain-text-splitters, langchain
  Attempting uninstall: zstandard
    Found existing installation: zstandard 0.19.0
    Uninstalling zstandard-0.19.0:
      Successfully uninstalled zstandard-0.19.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.6.3
    Uninstalling typing_extensions-4.6.3:
      Successfully uninstalled typing_extensions-4.6.3
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
  Attempting uninstall: orjson
    Found existing installation: orjson 3.9.1
    Uninstalling orjson-3.9.1:
      Successfully uninstalled orjson-3.9.1
  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.5.0
    Uninstalling annotated-types-0.5.0:
      Successfully uninstalled annotated-types-0.5.0
  Attempting uninstall: requests-toolbelt
    Found existing installation: requests-toolbelt 0.10.1
    Uninstalling requests-toolbelt-0.10.1:
      Successfully uninstalled requests-toolbelt-0.10.1
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.6.3
    Uninstalling pydantic_core-2.6.3:
      Successfully uninstalled pydantic_core-2.6.3
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.9
    Uninstalling pydantic-1.10.9:
      Successfully uninstalled pydantic-1.10.9
  Attempting uninstall: langsmith
    Found existing installation: langsmith 0.0.92
    Uninstalling langsmith-0.0.92:
      Successfully uninstalled langsmith-0.0.92
  Attempting uninstall: langchain
    Found existing installation: langchain 0.0.300
    Uninstalling langchain-0.0.300:
      Successfully uninstalled langchain-0.0.300
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf 23.8.0 requires cupy-cuda11x>=12.0.0, which is not installed.
cuml 23.8.0 requires cupy-cuda11x>=12.0.0, which is not installed.
dask-cudf 23.8.0 requires cupy-cuda11x>=12.0.0, which is not installed.
apache-beam 2.46.0 requires dill<0.3.2,>=0.3.1.1, but you have dill 0.3.7 which is incompatible.
apache-beam 2.46.0 requires pyarrow<10.0.0,>=3.0.0, but you have pyarrow 11.0.0 which is incompatible.
chex 0.1.82 requires numpy>=1.25.0, but you have numpy 1.23.5 which is incompatible.
chromadb 0.4.12 requires pydantic<2.0,>=1.9, but you have pydantic 2.11.3 which is incompatible.
cudf 23.8.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.0.2 which is incompatible.
cudf 23.8.0 requires protobuf<5,>=4.21, but you have protobuf 3.20.3 which is incompatible.
cuml 23.8.0 requires dask==2023.7.1, but you have dask 2023.9.0 which is incompatible.
dask-cuda 23.8.0 requires dask==2023.7.1, but you have dask 2023.9.0 which is incompatible.
dask-cuda 23.8.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.0.2 which is incompatible.
dask-cudf 23.8.0 requires dask==2023.7.1, but you have dask 2023.9.0 which is incompatible.
dask-cudf 23.8.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.0.2 which is incompatible.
distributed 2023.7.1 requires dask==2023.7.1, but you have dask 2023.9.0 which is incompatible.
fastapi 0.98.0 requires pydantic!=1.8,!=1.8.1,<2.0.0,>=1.7.4, but you have pydantic 2.11.3 which is incompatible.
google-cloud-bigquery 2.34.4 requires packaging<22.0dev,>=14.3, but you have packaging 24.2 which is incompatible.
jupyterlab-lsp 4.2.0 requires jupyter-lsp>=2.0.0, but you have jupyter-lsp 1.5.1 which is incompatible.
kfp 2.0.1 requires google-cloud-storage<3,>=2.2.1, but you have google-cloud-storage 1.44.0 which is incompatible.
kfp 2.0.1 requires requests-toolbelt<1,>=0.8.0, but you have requests-toolbelt 1.0.0 which is incompatible.
momepy 0.6.0 requires shapely>=2, but you have shapely 1.8.5.post1 which is incompatible.
pymc3 3.11.5 requires numpy<1.22.2,>=1.15.0, but you have numpy 1.23.5 which is incompatible.
pymc3 3.11.5 requires scipy<1.8.0,>=1.7.3, but you have scipy 1.11.2 which is incompatible.
raft-dask 23.8.0 requires dask==2023.7.1, but you have dask 2023.9.0 which is incompatible.
torchdata 0.6.0 requires torch==2.0.0, but you have torch 2.0.1 which is incompatible.
ydata-profiling 4.3.1 requires pydantic<2,>=1.8.1, but you have pydantic 2.11.3 which is incompatible.
ydata-profiling 4.3.1 requires scipy<1.11,>=1.4.1, but you have scipy 1.11.2 which is incompatible.
Successfully installed annotated-types-0.7.0 httpcore-1.0.8 httpx-0.28.1 langchain-0.3.23 langchain-core-0.3.51 langchain-text-splitters-0.3.8 langsmith-0.3.30 orjson-3.10.16 packaging-24.2 pydantic-2.11.3 pydantic-core-2.33.1 requests-toolbelt-1.0.0 typing-extensions-4.13.2 typing-inspection-0.4.0 zstandard-0.23.0
Note: you may need to restart the kernel to use updated packages.

In [149]:
agent_level = 2
query = "What is Amazon's industry and tell me whats in its description?"

context = secure_retrieve(query, agent_level=agent_level)

prompt = f"""Agent Level: {agent_level}
Query: {query}
Relevant Context:
{context}

Instructions: Answer the query using only the above context."""

first_pass_result=test_model(tokenizer, query_pipeline, prompt)
first_pass_result

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(

Test inference: 2.282 sec.
Result: Agent Level: 2
Query: What is Amazon's industry?
Relevant Context:
Company: Amazon
Rating: 3.8
Location: 25 office locations in United States
Industry: Internet & Web Services
Description: All Amazon teams and businesses, from Prime delivery to AWS, are guided by four key tenets: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking. We are driven by the excitement of building technologies, inventing products, and providing services that transform the way our customers live their lives and run their businesses.

Company: Adecco
Rating: 3.7
Location: 10151 Deerwood Park Blvd, Bldg 400
Industry: Staffing & Subcontracting
Description: eBay is where the world goes to shop, sell, and give. Every day, our professionals connect millions of buyers and sellers around the globe, empowering people and creating opportunity. We're on a mission to build a better, more connected form of commerce that benefits individuals, businesses, and society. We create stronger connections between buyers and sellers, offering product experiences that are fast, mobile and secure. At eBay, we develop technologies that enable connected commerce and make every interaction effortlessand more human. And we are doing it on a global scale, providing everyone with the chance to participate and create value.

Instructions: Answer the query using only the above context.

Answer: Amazon's industry is Internet & Web Services.

In [154]:
refined_prompt = f"""
You are an intelligence assitant.

Based on the following extracted information, write a clear and concise answer to the original query.

Original Query: {query}

Extracted Information:
{first_pass_result}

Instruction:
"""

final_answer = test_model(tokenizer, query_pipeline, refined_prompt)
print("Final Answer:", final_answer)

Test inference: 2.591 sec.
Final Answer:
You are an intelligence assitant.

Based on the following extracted information, write a clear and concise answer to the original query.

Original Query: What is Amazon's industry?

Extracted Information:
Agent Level: 2
Query: What is Amazon's industry?
Relevant Context:
Company: Amazon
Rating: 3.8
Location: 25 office locations in United States
Industry: Internet & Web Services
Description: All Amazon teams and businesses, from Prime delivery to AWS, are guided by four key tenets: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking. We are driven by the excitement of building technologies, inventing products, and providing services that transform the way our customers live their lives and run their businesses.

Company: Adecco
Rating: 3.7
Location: 10151 Deerwood Park Blvd, Bldg 400
Industry: Staffing & Subcontracting
Description: eBay is where the world goes to shop, sell, and give. Every day, our professionals connect millions of buyers and sellers around the globe, empowering people and creating opportunity. We're on a mission to build a better, more connected form of commerce that benefits individuals, businesses, and society. We create stronger connections between buyers and sellers, offering product experiences that are fast, mobile and secure. At eBay, we develop technologies that enable connected commerce and make every interaction effortlessand more human. And we are doing it on a global scale, providing everyone with the chance to participate and create value.

Instructions: Answer the query using only the above context.

Answer: Amazon's industry is Internet & Web Services.

Instruction:

Please answer the query with clear and concise information based on the extracted information.

In [158]:
def test_model(tokenizer, pipeline, prompt_to_test):
    """
    Perform a query
    Return the result as a string
    """
    time_1 = time()
    sequences = pipeline(
        prompt_to_test,
        do_sample=True,
        top_k=10,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        max_length=2048,  # or any suitable length
    )
    time_2 = time()
    print(f"Test inference: {round(time_2 - time_1, 3)} sec.")

    results = [seq['generated_text'] for seq in sequences]
    return results[0] if results else ""

agent_level = 2
query = "What is Amazon's industry and tell me whats in its description about its 4 key tenets?"

context = secure_retrieve(query, agent_level=agent_level)

prompt = f"""Agent Level: {agent_level}
Query: {query}
Relevant Context:
{context}
"""

first_pass_result = test_model(tokenizer, query_pipeline, prompt)

refined_prompt = f"""
You are an intelligence assitant.

Based on the following extracted information, write a clear and concise answer to the original query.

Original Query: {query}

Extracted Information:
{first_pass_result}

Instruction:Write a short answer using only the information above. Be factual and do not add any assumptions.

"""

final_answer = test_model(tokenizer, query_pipeline, refined_prompt)
print("Final Answer:", final_answer)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Test inference: 3.741 sec.
Test inference: 12.773 sec.
Final Answer:
You are an intelligence assitant.

Based on the following extracted information, write a clear and concise answer to the original query.

Original Query: What is Amazon's industry and tell me whats in its description about its 4 key tenets?

Extracted Information:
Agent Level: 2
Query: What is Amazon's industry and tell me whats in its description about its 4 key tenets?
Relevant Context:
Company: Amazon
Rating: 3.8
Location: 25 office locations in United States
Industry: Internet & Web Services
Description: All Amazon teams and businesses, from Prime delivery to AWS, are guided by four key tenets: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking. We are driven by the excitement of building technologies, inventing products, and providing services that transform the way our customers live their lives and run their businesses.

Company: Adecco
Rating: 3.7
Location: 10151 Deerwood Park Blvd, Bldg 400
Industry: Staffing & Subcontracting
Description: eBay is where the world goes to shop, sell, and give. Every day, our professionals connect millions of buyers and sellers around the globe, empowering people and creating opportunity. We're on a mission to build a better, more connected form of commerce that benefits individuals, businesses, and society. We create stronger connections between buyers and sellers, offering product experiences that are fast, mobile and secure. At eBay, we develop technologies that enable connected commerce and make every interaction effortlessand more human. And we are doing it on a global scale, providing everyone with the chance to participate and create value.

Ask: What is Amazon's description of its 4 key tenets, and how does it compare to Adecco's description of its industry?

Instruction:Write a short answer using only the information above. Be factual and do not add any assumptions.

Answer: Amazon's description of its 4 key tenets are customer obsession, passion for invention, commitment to operational excellence, and long-term thinking. These tenets guide all of Amazon's teams and businesses, from Prime delivery to AWS. In contrast, Adecco's description of its industry is staffing and subcontracting, with a mission to build a better and more connected form of commerce that benefits individuals, businesses, and society. While both companies are focused on connecting buyers and sellers, Amazon's emphasis is on creating effortless and connected commerce experiences, while Adecco's focus is on developing technologies that enable staffing and subcontracting.

In [14]:
loader = PyMuPDFLoader("/kaggle/input/lawandorder/Bharatiya_Nyay_(Second)_Sanhita_2023.pdf")
document1 = loader.load()

## Split data in chunks

We split data in chunks using a recursive character text splitter.

In [ ]:
text_splitter = RecursiveCharacterTextSplitter(chunk_size=256, chunk_overlap=20)
all_splits = text_splitter.split_documents(documents)

## Creating Embeddings and Storing in Vector Store

Create the embeddings using Sentence Transformer and HuggingFace embeddings.

In [ ]:
model_name = "sentence-transformers/all-mpnet-base-v2"
model_kwargs = {"device": "cuda"}

embeddings = HuggingFaceEmbeddings(model_name=model_name, model_kwargs=model_kwargs)

Initialize ChromaDB with the document splits, the embeddings defined previously and with the option to persist it locally.

In [ ]:
vectordb = Chroma.from_documents(documents=all_splits, embedding=embeddings, persist_directory="chroma_db")

## Initialize chain

## Test the Retrieval-Augmented Generation 


We define a test function, that will run the query and time it.

In [74]:
def test_rag(qa, query):
    print(f"Query: {query}\n")
    time_1 = time()
    result = qa.run(query)
    time_2 = time()
    print(f"Inference time: {round(time_2-time_1, 3)} sec.")
    print("\nResult: ", result)

Let's check few queries.

In [75]:
query = """
you are an intelligent assistant to assist educators to generate curricullam based question on the provideed pdf of class 8th mathematics
Instructions for Generating Mathematics Problems:-
Topic Coverage: Ensure that the problems you create span the various topics covered in this chapter.
Originality: The questions you generate should not be identical to or minor variations of the questions already present in the PDFs. Instead, use the concepts and examples as a foundation to create entirely new problems.

Now generate 2 mathematics questions.
"""
test_rag(qa, query)

NameError: name 'qa' is not defined

## Document sources

Let's check the documents sources, for the last query run.


We used Langchain, ChromaDB and Llama 2 as a LLM to build a Retrieval Augmented Generation solution. 
For IIIT DHARWAD, FOR THE TOPIC OF 'CURRICULAM BASED QUESTION GENERATION'-(FOR EXACT TOPIC AND QUESTION RELATIONAL MATCHES)

## WE SHALL CLEAR DOWN THE DATABASE MEMORY FOR NEXT BOOK READ

In [139]:
import shutil as st
st.rmtree("/kaggle/working/chroma_db")

# References  

[1] Murtuza Kazmi, Using LLaMA 2.0, FAISS and LangChain for Question-Answering on Your Own Data, https://medium.com/@murtuza753/using-llama-2-0-faiss-and-langchain-for-question-answering-on-your-own-data-682241488476  

[2] Patrick Lewis, Ethan Perez, et. al., Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks, https://browse.arxiv.org/pdf/2005.11401.pdf 

[3] Minhajul Hoque, Retrieval Augmented Generation: Grounding AI Responses in Factual Data, https://medium.com/@minh.hoque/retrieval-augmented-generation-grounding-ai-responses-in-factual-data-b7855c059322  

[4] Fangrui Liu	, Discover the Performance Gain with Retrieval Augmented Generation, https://thenewstack.io/discover-the-performance-gain-with-retrieval-augmented-generation/

[5] Andrew, How to use Retrieval-Augmented Generation (RAG) with Llama 2, https://agi-sphere.com/retrieval-augmented-generation-llama2/   

[6] Yogendra Sisodia, Retrieval Augmented Generation Using Llama2 And Falcon, https://medium.com/@scholarly360/retrieval-augmented-generation-using-llama2-and-falcon-ed26c7b14670